---
- hosts: web
  remote_user: ubuntu
  tasks:
  - name: create dir for nginx
    file:
      path: /opt/nginx/www
      state: directory
      mode: '0755'
  - name: install nginx latest version
    apt:
      name: nginx
      state: latest
  - name: start nginx
    service:
      name: nginx
      state: started

